#!/usr/bin/ruby
# TODO: -w

# Usage: btc-price

ENV['BUNDLE_GEMFILE'] = File.dirname(__FILE__) + "/Gemfile"

require 'rubygems'
require 'bundler/setup'

require_relative 'bitcoin-price'

module BtcKit
	class BtcPriceGet
		def main
			puts BtcPrice.new.btc_localbitcoins_manual
		end
	end
end

if __FILE__ == $0
	BtcKit::BtcPriceGet.new.main
end
