#!/usr/bin/ruby -w

# Usage: btc-wallet-price [--xosd]

ENV['BUNDLE_GEMFILE'] = File.dirname(__FILE__) + "/Gemfile"

require 'rubygems'
require 'bundler/setup'

require 'net/http'
require 'json'

require_relative 'config'

module BtcKit
	class BtcWalletPrice
		def main
			raw = false
			xosd = false

			until ARGV.empty
				case ARGV.shift
				when "--xosd" then xosd = true
				when "--raw" then raw = true
				else puts "Usage: btc-wallet-price [--xosd] [--raw]"; exit 1
				end
			end

			config = Config.new

			json = JSON.parse(Net::HTTP.get_response(URI.parse "http://bitcash.cz/market/api/BTCCZK/ticker.json").body)
			raise unless json["result"] == "success"
			ticker = json["data"]["sell"]["value"]

			initialCZK = config.initial_czk
			currentCZK = config.wallet_btc * ticker
			delta = currentCZK - initialCZK
			deltaPercent = (delta / initialCZK) * 100.0

			result = if raw
				"%.2f" % currentCZK
			else
				"%.2f Kč (%+.2f Kč, %+.2f%%)" % [currentCZK, delta, deltaPercent]
			end

			if xosd
				system "xosdutilctl", "echo", result
			else
				puts result
			end
		end
	end
end

if __FILE__ == $0
	BtcKit::BtcWalletPrice.new.main
end
