#!/usr/bin/ruby

# Usage: btcreport [price of Bitcoin]

ENV['BUNDLE_GEMFILE'] = File.dirname(__FILE__) + "/Gemfile"

require 'rubygems'
require 'bundler/setup'

require 'action_view'

require_relative 'bitstamp'
require_relative 'config'
require_relative 'bank'

module BtcKit
	class BtcReport
		include ActionView::Helpers::NumberHelper

		def main
			config = Config.new
			creds = config.credentials
			@bitstamp = Bitstamp.new(creds[:username], creds[:password])
			@bank = Bank.new(config.bank_filename)

			balance = @bitstamp.balance
			dollars, btcs = balance[:USD], balance[:BTC]

			initialCZK = config.initial_czk

			if ARGV[0].present?
				price = ARGV[0].to_f
			else
				price = @bitstamp.ticker
			end

			currentCZK = @bank.exchange(price * btcs + dollars, "USD", "CZK").cents.to_f 
			delta = currentCZK - initialCZK

			deltaPercent = (delta / initialCZK) * 100.0
			puts "%.3f $/BTC (%+.2f Kč, %+.2f%%) [%s]" % [price, delta, deltaPercent, number_to_currency(currentCZK, precision: 0, delimiter: ' ', format: '%n %u', unit: 'Kč')]
		end
	end
end

if __FILE__ == $0
	BtcKit::BtcReport.new.main
end
